export const CACHE_TAGS = {
    NAVBAR: 'navbar',
    SETTINGS: 'settings',
    FOOTER: 'footer',
    ARTICLES: 'articles',
    FEATURED_ARTICLES: 'featured_articles',
    HOMEPAGE: 'homepage',
    ABOUTPAGE: 'about_page',
    CONTACTPAGE: 'contact_page',
    PACKAGEPAGE: 'package_page',
    FACULTYPAGE: 'faculty_page',
    NOTICESPAGE: 'notices_page',
    BLOGPAGE: 'blog_page',
    FAQPAGE: 'faq_page',
    TERMSPAGE: 'terms_page',
    TEACHERS: 'teachers',
    NOTICES: 'notices',
    CATEGORIES: 'categories',
    PACKAGES: 'packages',
    TESTIMONIALS: 'testimonials',
} as const;
